apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  name: vijaysmks260508
  project: defaultproject
spec:
  blueprint:
    name: custom-cni
    version: v4
  config:
    autoApproveNodes: true
    installerTtl: 360
    kubeletConfigurationOverrides: |
      clusterDNS:
      - 169.254.20.10
    kubeletExtraArgs:
      max-pods: "250"
    kubernetesVersion: v1.35.0
    network:
      cni:
        name: CNI-via-Blueprint
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.96.0.0/12
    nodes:
    - arch: amd64
      hostname: masterworker-th7ch4-1
      operatingSystem: Ubuntu22.04
      privateIP: 10.0.0.204
      roles:
      - ControlPlane
      - Worker
      ssh:
        ipAddress: 129.146.175.234
    ssh:
      port: "22"
      privateKeyPath: /Users/vijaysamanthapuri/Documents/private_keys/oci_mks.key
      username: ubuntu
  type: mks
