apiVersion: infra.k8smgmt.io/v3
kind: Addon
metadata:
  name: karpenter-nodepool
  project: defaultproject
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/karpenter-nodepool/nodepool.yaml
    type: Yaml
  namespace: kube-system
  sharing: {}
  version: v3
  versionState: active
